### ISSUE TITLE
[Bug] Rules not disable

### ISSUE THREAD

**Issue by Kristinita** [Microsoft/DevSkim-Sublime-Plugin#2]
### 1. Summary

I can't disable rules.

### 2. Expected behavior

Disabling unexpected rules.

### 3. Actual behavior

Rules not disable.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install DevSkim via package Control → I restart Sublime Text → for example, I open my file `test.md`, with «todo» word. I save my file → I see quick panel →

![TODO panel](http://i.imgur.com/LVd67zL.png)

<kbd>Enter</kbd> → `Suppress this rule for:` → <kbd>Left_Click</kbd> to permanently → <kbd>Ctrl+S</kbd> → I see quick panel again, rule not disable for me.

### 5. Environment

**Operating system and version:**
Windows 10 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by scovetta** [comment]
Confirmed, thanks for this bug report! We'll get a fix out shortly. As a temporary workaround, you can choose a 365-day suppression and then manually change the date out to 9999-01-01 (or any date far in the future).

If you want to globally ignore a rule like this, you can add it to the DevSkim user settings:

```
{
  /* Globally suppress these rules (list of rule IDs, like "DS123456") */
  "suppress_rules": [
    "DS176209"
  ]
}
```

**Comment by scovetta** [comment]
This has been fixed and is now available via PackageControl.
