### ISSUE TITLE
Unable to open default settings

### ISSUE THREAD

**Issue by scovetta** [Microsoft/DevSkim-Sublime-Plugin#3]
When opening DevSkim default settings, a blank window is opened, and an error is shown in the console:

`Unable to open /C/Users/(username)/AppData/Roaming/Sublime Text 3/Packages/DevSkim-Sublime-Plugin/DevSkim.sublime-settings`

That path doesn't exist, because DevSkim is installed in **Installed Packages**.

**Environment:**
Windows 10 / 64-bit.
ST3 build 3126

**Comment by Kristinita** [comment]
@scovetta, users may install [**PackageResourceViewer**](https://packagecontrol.io/packages/PackageResourceViewer) → `PackageResourceViewer: Open Resource` → `DevSkim.sublime-settings` → settings file is open.

Also, users may extract package to `Packages` folder use `PackageResourceViewer: Extract Package`. And use [**ExtractSublimePackage**](https://packagecontrol.io/packages/Extract%20Sublime%20Package) plugin, users may run `Extract Sublime Package: Extract all packages`.

Thanks.

**Comment by scovetta** [comment]
Fixed in https://github.com/Microsoft/DevSkim-Sublime-Plugin/commit/a11084c9e3436ee8b64aca46734a7a1561168a5c.
